# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-05-16 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200516_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='New Title'),
        ),
    ]
