# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-05-29 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200517_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=250),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='integer',
            field=models.BigIntegerField(default=0),
        ),
    ]
