# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-05-29 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200529_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='email',
            field=models.EmailField(max_length=250, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='integer',
            field=models.BigIntegerField(default=0, verbose_name='Integer'),
        ),
    ]
