# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-05-31 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post_models'},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('title', 'slug')]),
        ),
    ]
