# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-05-31 07:35
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200531_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.upload_location, verbose_name='Image'),
        ),
    ]
