# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-05-31 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200531_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Please use the unique title.', max_length=120),
        ),
    ]
